# Site settings
title: "&lt;RAUL_GARCIA&gt;"
email: raul.garcia.gomez1982@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "ESte es mi pequeño portfolio digital, donde muestro parte de mi trabajo."
keywords: "desarrollo, css, tailwind, node.js, web, javascript, JAVA, HTML"
skills: "Desarrollador Web • PHP • Java • Python • JavaScript • SQL • C/C++ • React • Angular • Azure • IA • Node.js • Tailwind • OpenCode • LM Studio"
meta_author: García Raúl

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1a3a52
  primary-rgb: "26,58,82"
  secondary: 2c3e50
  secondary-dark: 0f1f2e
  accent: 0099CC
  navbar-active: 0099CC

# Footer settings
footer:
  copyright: Raúl García
  location: C. Madrid, España
  social: Redes Sociales
  credits: Créditos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Raulito007/Raulito007.github.io
  - title: linkedin
    url: https://www.linkedin.com/in/ra%C3%BAl-garc%C3%ADa-g%C3%B3mez-312961185/
# Postal address (add as many lines as necessary)

address:
  - line: Móstoles
  - line: C.Madrid, España

# Credits content
credits: 'Esta web ha sido creada utilizando Jekyll y la plantilla Freelancer.'

# External links
links:
  jekyll: https://jekyllrb.com/
  freelancer: https://github.com/jeromelachaud/freelancer-theme

# Version
version: '7 de abril de 2026'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
